stages:
  train:
    cmd: jupyter nbconvert --to notebook --execute mtbi_prediction_task.ipynb
    deps:
    - data_archive.zip
    - mtbi_prediction_task.ipynb
    params:
    - params.json:
      - lr
    outs:
    - model.joblib:
        cache: false
    metrics:
    - metrics.json:
        cache: false
