name: run-my-experiment
on: [pull_request]
jobs:
  dvc_exp_run:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Run experiment
      run: |
        echo "At point 0"
        # gcloud auth application-default login --quiet
        echo "At point 1"
        pip install -r requirements.txt
        echo "At point 2"
        dvc pull
        echo "At point 3"
        find data_archive.zip
        echo "At point 4"
        dvc repro
        echo "At point 5"
    - name: Commit and push experiment results
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |     
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Results of the last experiment"
        git push origin HEAD:${{ github.ref }}
